title: 'Emergent Anomalies'
default_lang: en
author:
  name: 'Alisha Awen'
  email: siren1@disroot.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Emergent Anomalies - Magazine, Stories, News and Podcast - Probing the Mysterous and Unexplained'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
